# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "Terminal-first AI chat for daily LLM work"
  homepage "https://github.com/jrniemiec/lore"
  version "0.9.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jrniemiec/lore/releases/download/v0.9.2/lore_0.9.2_darwin_amd64.tar.gz"
    sha256 "1b7927655e5c3ce8e70f716537588df1031c118f8c3d8befa20862a7868c6931"

    define_method(:install) do
      bin.install "lore"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jrniemiec/lore/releases/download/v0.9.2/lore_0.9.2_darwin_arm64.tar.gz"
    sha256 "39bf788d954716a4491782d7a2541f94b69e8482238346fccda1c65365a75f3a"

    define_method(:install) do
      bin.install "lore"
    end
  end

  test do
    system "#{bin}/lore --nw --status"
  end
end
